name: Ejecutar Cron Job en el backend

on:
  schedule:
    - cron: '*/1 * * * *'  # Ejecutar cada 5 minutos (ajustable según tus necesidades)
  workflow_dispatch:

jobs:
  run-cron-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Hacer solicitud GET al backend para ejecutar el cron
      run: |
        curl -X GET "https://meditrack-2vkl.onrender.com/cron/ejecutar-cron?token=${{ secrets.CRON_JOB_SECRET }}"
